//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMP494_594.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concentration
    {
        public Concentration()
        {
            this.StudentAccount = new HashSet<StudentAccount>();
            this.Courses = new HashSet<Courses>();
        }
    
        public int Id { get; set; }
        public string ConName { get; set; }
        public string MiniCredit { get; set; }
    
        public virtual ICollection<StudentAccount> StudentAccount { get; set; }
        public virtual ICollection<Courses> Courses { get; set; }
    }
}
