//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMP494_594.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public Courses()
        {
            this.Concentration = new HashSet<Concentration>();
        }
    
        public int Id { get; set; }
        public string CourseName { get; set; }
        public string Credit { get; set; }
        public string Grade { get; set; }
    
        public virtual ICollection<Concentration> Concentration { get; set; }
    }
}
