//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMP494_594.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERmodelContainer : DbContext
    {
        public ERmodelContainer()
            : base("name=ERmodelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StudentAccount> StudentAccounts { get; set; }
        public virtual DbSet<Concentration> Concentrations { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
    }
}
