//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMP494_594.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAccount
    {
        public StudentAccount()
        {
            this.Concentrations = new HashSet<Concentration>();
        }
    
        public int Id { get; set; }
        public long Wnumber { get; set; }
        public Nullable<short> GPA { get; set; }
    
        public virtual ICollection<Concentration> Concentrations { get; set; }
    }
}
